name: Trigger Repo B on Master Commit

on:
  push:
    branches:
      - master

jobs:
  trigger-repo-b:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Trigger Repo B's Workflow
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.repos.createDispatchEvent({
                owner: 'Ankit0506',
                repo: 'repo-b',
                event_type: 'run-hel-script'
              });
            } catch (error) {
              console.error('Error triggering Repo B:', error);
              throw error; // Fail the job on error
            }
        env:
          GH_TOKEN: ${{ secrets.REPO_B_TOKEN }}
