# This GitHub Actions workflow is designed to automate the release process for a project.
# It is triggered by pull request reviews and pull request events on the main branch.
#
# The workflow consists of several jobs: comments added in respective sections

# Each job has specific steps to perform its tasks, including checking out code, configuring AWS credentials, and running necessary commands.
name: Release Workflow
on: [push]

jobs:

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    steps:
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v2.0.0
        with:
          helmfile-version: v0.157.0
          helm-version: v3.13.1
          install-kubectl: false
