# name: Trigger syc_qa_auto workflow when there is a push to ankit branch

# on:
#   push:
#     branches:
#       - master 
# jobs:
#   trigger:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Trigger Another Repository Workflows
#         run: |
#           # Set the required variables
#           repo_owner="Ankit0506"  # Replace with actual repository owner
#           repo_name="repo-b"  # Replace with actual repository name
#           branch_name="main"  # Specify the branch you want to trigger in the target repo
          
#           curl -L \
#             -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/${repo_owner}/${repo_name}/actions/workflows/jobsync.yml/dispatches \
#             -d "{\"ref\":\"${branch_name}\"}"  # Specify the branch for the target repo
