name: Build and Deploy pip

on:
  push:
    branches: [master]

jobs:
  runtimeInfo: 
    name: Print Input & Environment details
    runs-on: self-hosted

    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "$BRANCH_NAME"


      # - name: Show Runtime Env Values
      #   run: |
      #     echo ""
      #     echo "Running Staging Release workflow with the following Env Values:"
      #     echo ""
      #     echo "Deploying Branch: ${{ env.BRANCH_NAME }}"
      #     echo "Deploying to Environment: ${{ github.event.inputs.environment }}"

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: |
        BRANCH_NAME="${{ env.BRANCH_NAME }}"
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy
      env:
        BRANCH_NAME: ${{ needs.build.outputs.BRANCH_NAME }}
      run: |
        echo "BRANCH_NAME=$BRANCH_NAME"
