name: Build Docker Image

on:
  push:
    branches:
      - 'master'
env:
  repository: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: echo ${{ env.BRANCH_NAME }}

      - name: Print branch name
        run: echo "$BRANCH_NAME"

      - name: repo name from env
        run: |
          echo "${{ env.repository }}/${{ env.BRANCH_NAME }}"
          echo "Repository Name: ${{ env.repository }}"
          echo "${{ env.BRANCH_NAME }}"
