name: Retrieve Branch Name
on:
  push:
    branches:
      - 'master'
permissions:
  id-token: write
  contents: write

env:
  organization: "abc"
  repository: "xyz"
  tag: "sha-${{ github.sha }}"
  full_env_name: "${{ github.base_ref }}-pr-${{ github.event.commits }}"
  remote_branch_name: "${{ github.repository }}/${{ github.base_ref }}${{ github.event.ref }}"
  branch: "${{ github.ref_name }}"
 
jobs:
  retrieve-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Build 
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
      #     BRANCH: ${{ env.organization }}/${{ env.repository }}
      #     BRANCH_NAME: ${{ env.remote_branch_name }}
      #     TAG_NAME: ${{ env.tag }}
      #     build-args: ${{ steps.args.outputs.build_args }}
      #     TAG: ${{ env.branch }}
      #   run: |
      #     echo $BRANCH
      #     echo $BRANCH_NAME
      #     echo $TAG_NAME
      #     echo $TAG


      - name: Parse JSON
        env:
          MY_JSON_DATA: ${{ vars.MY_JSON_DATA }}
        run: |
          echo "Original JSON: $MY_JSON_DATA"
          # Parse JSON with jq
          VALUE=$(echo "$VARIABLETEST" | jq -r '.key_name')
          echo "Parsed Value: $VALUE"    
