name: Retrieve Branch Name
on:
  push:
    branches:
      - 'master'
permissions:
  id-token: write
  contents: write

env:
  organization: "abc"
  repository: "xyz"
  tag: "sha-${{ github.sha }}"
  full_env_name: "${{ github.base_ref }}-pr-${{ github.event.commits }}"
  remote_branch_name: "${{ github.repository }}/${{ github.base_ref }}/${{ github.event.ref }}"
  branch: "${{ github.event.ref }}"
 
jobs:
  retrieve-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Branch Name
        id: set_branch_name
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "branch_name=ankit_${TIMESTAMP}" >> $GITHUB_ENV
          q="${{ env.branch_name }}"
          echo "Value of q: $q"

      - name: Build 
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          BRANCH: ${{ env.organization }}/${{ env.repository }}
          BRANCH_NAME: ${{ env.remote_branch_name }}
          TAG_NAME: ${{ env.tag }}
          build-args: ${{ steps.args.outputs.build_args }}
          TAG: ${{ env.branch }}
        run: |
          echo $BRANCH
          echo $BRANCH_NAME
          echo $TAG_NAME
          echo $TAG

            
