name: Build Docker Image

on:
  push:
    branches:
      - 'master'
env:
  repository: "hello-world-1"
  #tag: "${{ github.event.inputs.branch }}"
  tag: "${{ github.ref }}"
  branch_name: "$BRANCH_NAME"
  remote_branch_name: "${{ github.repository }}/${{ env.BRANCH_NAME }}"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build Docker image
        #run: docker build -t tedmiston/tag-example:${{ env.BRANCH_NAME }} .
        run: echo ${{ env.BRANCH_NAME }}

      - name: Print branch name
        run: echo "$BRANCH_NAME"

      - name: Print remote branch name
        run: |
          REMOTE_BRANCH="${{ env.remote_branch_name }}"
          echo "$REMOTE_BRANCH"
