name: Trigger Workflow on Push

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your test commands here
          # For example, if using Node.js:
          # npm install
          # npm test

      - name: Trigger Another Repository Workflow
        run: |
          # Set the required variables
          repo_owner="REPOSITORY_OWNER"  # Replace with actual repository owner
          repo_name="REPOSITORY_NAME"      # Replace with actual repository name
          event_type="trigger-workflow"
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_B_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${repo_owner}/${repo_name}/dispatches \
            -d "{\"event_type\":\"$event_type\"}"
