name: Parse JSON from Variable

on: [push]

jobs:
  parse_json:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Parse JSON
        env:
          MY_JSON_DATA: ${{ vars.MY_JSON_DATA }}
        run: |
          echo "Original JSON: $MY_JSON_DATA"
          # Parse JSON with jq
          VALUE=$(echo "$MY_JSON_DATA" | jq -r '.key_name')
          echo "Parsed Value: $VALUE"
