name: Retrieve Branch Name
on:
  push:
    branches:
      - 'master'

jobs:
  retrieve-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Branch Name
        id: set_branch_name
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "branch_name=ankit_${TIMESTAMP}" >> $GITHUB_ENV

      # - name: Print Branch Name
      #   run: echo "Branch Name:${{ env.branch_name }}"

      - name: Assign to Variable Q
        run: |
          q="${{ env.branch_name }}"
          echo "Value of q: $q"
